spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/game
    username: shavalad
    password: asdfg456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: game-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: 'com.keyseven.game.dtos,com.keyseven.genre.dtos'  # Trust the correct packages
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.value.delegate.trusted.packages: '*'  # Trust all packages
    listener:
      concurrency: 3  # Set concurrency for Kafka listener (can adjust based on load)
logging:
  level:
    com.keyseven.game.services.Impl.GenreCacheService: DEBUG  # Debug level for genre cache service
server:
  port: 8050