spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/genre
    username: shavalad
    password: asdfg456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    # The producer does not need a consumer configuration as this service is just publishing events
server:
  port: 8060
