spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: shavalad
    password: asdfg456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090
