spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/realms/key-seven"
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

