version: '3.9'

services:
  postgres:
    container_name: ms_postgres_sql
    image: postgres
    environment:
      POSTGRES_USER: shavalad
      POSTGRES_PASSWORD: asdfg456
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5433
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ms_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5433/keycloak
      KC_DB_USERNAME: shavalad
      KC_DB_PASSWORD: asdfg456
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    networks:
      - microservices-net
    command: start-dev

volumes:
  postgres:

networks:
  microservices-net:
    driver: bridge
